### ISSUE TITLE
Frequent Crashes in Android App (Audienzz Library v0.4.5, React Native 0.67.5)

### ISSUE THREAD

**Issue by jlopezdominguez** [audienzz/react-native-audienzz#34]
Hi, 

We have recently observed that a significant number of crashes reported in Firebase Crashlytics for our app are related to the Audienzz library.

**Library Version:** We are currently using version 0.4.5 of the Audienzz library with React Native version 0.67.5.
**Platform Affected:** The issue appears to be isolated to our Android application.
**Crash Details:** Below are the three main types of crashes we have encountered over the last month regarding the Audienzz library:

![image](https://github.com/audienzz/react-native-audienzz/assets/150150490/8ef4f614-930a-460a-8a53-1e2ff4ed996a)

<details>
  <summary>1. AdView.java line 115
(com.appnexus.opensdk.AdView)</summary>
  
  
  ```
  Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.view.ViewConfiguration.get(ViewConfiguration.java:579)
       at android.view.View.<init>(View.java:5736)
       at android.view.View.<init>(View.java:5920)
       at android.view.ViewGroup.<init>(ViewGroup.java:712)
       at android.widget.FrameLayout.<init>(FrameLayout.java:99)
       at android.widget.FrameLayout.<init>(FrameLayout.java:94)
       at com.appnexus.opensdk.AdView.<init>(AdView.java:115)
       at com.appnexus.opensdk.AdView.<init>(AdView.java:111)
       at com.appnexus.opensdk.AdView.<init>(AdView.java:107)
       at com.appnexus.opensdk.BannerAdView.<init>(BannerAdView.java:122)
       at com.reactnativeaudienzz.RTCAppNexusBanner.<init>(RTCAppNexusBanner.java:38)
       at com.reactnativeaudienzz.RTCAppNexusBannerView.<init>(RTCAppNexusBannerView.java:37)
       at com.reactnativeaudienzz.RTCAppNexusBannerManager.createViewInstance(RTCAppNexusBannerManager.java:39)
       at com.reactnativeaudienzz.RTCAppNexusBannerManager.createViewInstance(RTCAppNexusBannerManager.java:22)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:909)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:984)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103);
  ```
  
</details>

<details>
  <summary>2. UTAdRequest.java line 93
(com.appnexus.opensdk.ut.UTAdRequest.execute)</summary>
  
  
  ```
  Fatal Exception: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@48200b8 rejected from java.util.concurrent.ThreadPoolExecutor@de28e91[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 135]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
       at com.appnexus.opensdk.ut.UTAdRequest.execute(UTAdRequest.java:93)
       at com.appnexus.opensdk.RequestManager.execute(RequestManager.java:66)
       at com.appnexus.opensdk.AdFetcher$RequestHandler.handleMessage(AdFetcher.java:264)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
  ```
  
</details>

<details>
  <summary>3. AdWebView.java line 584
(com.appnexus.opensdk.AdWebView.openInAppBrowser)</summary>
  
  
  ```
 Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context com.appnexus.opensdk.AdView.getContext()' on a null object reference
       at com.appnexus.opensdk.AdWebView.openInAppBrowser(AdWebView.java:584)
       at com.appnexus.opensdk.AdWebView.access$2200(AdWebView.java:73)
       at com.appnexus.opensdk.AdWebView$RedirectWebView$1.onPageFinished(AdWebView.java:1161)
       at WV.DW.b(chromium-TrichromeWebViewGoogle6432.aab-stable-631209933:12)
       at WV.j6.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-631209933:261)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
  ```
  
</details>

Any tips on how could we solve this ?

Thanks

**Comment by jlopezdominguez** [comment]
Hi,

After upgrading React Native from 0.67.5 to 0.72.12, we're still encountering the same Crashlytics reports.

Additionally, we have observed this crash in another app that uses version 0.5.5 of this library(running React Native 0.67.5, the RN 0.72.12 upgrade hasn't been published yet).

Could you provide any updates or clues on when these bugs might be resolved?

Thank you.
